#!/bin/bash          
######################################################################
#
#       @# Create ServerBlock 
#
#       Copyright (c) Argoden.
#       All Rights Reserved.
#
#       This Module contains Proprietary Information
#       and should be treated as Confidential.
#
#  Author:  Aleksander Prokofiev
#  Date:    2013-09-22
#  Version: VERNUMB
#
######################################################################
function usage(){
cat <<EOF
usage: $0 <HOSTNAME>
------------------------------

Creates virtual host in NGINX and restart server.
EOF
}

if [ -z "$1" ]; then
usage
exit
fi

NGINX_HOME="/etc/nginx";

SPECFILE="
server
{
    listen 82;
    server_name $1.argoden.com;
    access_log /var/log/nginx/$1.access.log;
    error_log /var/log/nginx/$1.error.log;
    root /var/www/$1;
    index index.html index.htm;
  
    # use fastcgi for all php files
    location ~ \.php$
    {
        fastcgi_pass unix:/var/run/php7.0-fpm.sock;
        fastcgi_index index.php;
    #    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
  
    # proxy
    #location / {
    #    proxy_pass http://127.0.0.1:86;
    #}

    # deny access to apache .htaccess files
    location ~ /\.ht
    {
        deny all;
    }
}
";


echo -e "$SPECFILE" > $NGINX_HOME/sites-available/$1
echo 
sudo ln -s $NGINX_HOME/sites-available/$1 $NGINX_HOME/sites-enabled/$1
sudo service nginx restart

