#!/bin/bash          
USAGE="\n 
This is will create users on debian unix system, \n
create MySQL database, and web area for specified user\n
\n
Sample $0 <USERNAME>\n
"
if [ -z "$1" ]; then
echo -e $USAGE 
exit
fi

useradd -m $1
passwd $1
usermod -s /bin/bash $1
usermod -a -G www-data $1
mkdir /var/www/$1
chmod 775 /var/www/$1
ln -s /var/www/$1 /home/$1/www
