#!/bin/bash          
######################################################################
#
#       @# Create ServerBlock 
#
#       Copyright (c) Argoden.
#       All Rights Reserved.
#
#       This Module contains Proprietary Information
#       and should be treated as Confidential.
#
#  Author:  Aleksander Prokofiev
#  Date:    2013-09-22
#  Version: VERNUMB
#
######################################################################
USAGE="\n 
This program will create new\n
server block on given system and\n 
restart nginx web server\n
\n
Sample $0 <SERVER_BLOCK>\n
"
if [ -z "$1" ]; then
echo -e $USAGE 
exit
fi

NGINX_HOME="/etc/nginx";

SPECFILE="
server
{
    server_name $1.argoden.com;
    access_log /var/log/nginx/$1.access.log;
    error_log /var/log/nginx/$1.error.log;
    root /var/www/$1;
    index index.html index.htm;
  
    # use fastcgi for all php files
    location ~ \.php$
    {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
    #    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
  
    # proxy
    #location / {
    #    proxy_pass http://127.0.0.1:86;
    #}

    # deny access to apache .htaccess files
    location ~ /\.ht
    {
        deny all;
    }
}
";


echo -e "$SPECFILE" > $1
sudo ln -s $NGINX_HOME/sites-available/$1 $NGINX_HOME/sites-enabled/$1
sudo service nginx restart
